name: eGlow
version: '2.1.1'
main: me.jqln.eGlow.EGlow
api-version: '1.21'
softdepend: ['PlaceholderAPI']
commands:
  glow:
    description: Make yourself glow
    usage: /<command> [color]
    aliases:
      - eglow
permissions:
  eglow.color.darkred:
    description: Allows user to set their glow to dark red
  eglow.color.red:
    description: Allows user to set their glow to red
  eglow.color.yellow:
    description: Allows user to set their glow to yellow
  eglow.color.gold:
    description: Allows user to set their glow to gold
  eglow.color.darkgreen:
    description: Allows user to set their glow to dark green
  eglow.color.green:
    description: Allows user to set their glow to green
  eglow.color.aqua:
    description: Allows user to set their glow to aqua
  eglow.color.darkaqua:
    description: Allows user to set their glow to dark aqua
  eglow.color.darkblue:
    description: Allows user to set their glow to dark blue
  eglow.color.blue:
    description: Allows user to set their glow to blue
  eglow.color.lightpurple:
    description: Allows user to set their glow to light purple
  eglow.color.darkpurple:
    description: Allows user to set their glow to dark purple
  eglow.color.white:
    description: Allows user to set their glow to white
  eglow.color.gray:
    description: Allows user to set their glow to gray
  eglow.color.darkgray:
    description: Allows user to set their glow to dark gray
  eglow.color.black:
    description: Allows user to set their glow to black